<?php
if (substr($_SERVER["REQUEST_URI"], -10) == "config.php") {
    header("Location:./");
};
$data['mikhmon'] = array('1' => 'mikhmon<|<fame1302', 'mikhmon>|>aWRja2JlaWQ=');

$data['MIKROTIKRUMAH'] = array('1' => 'MIKROTIKRUMAH!10.5.50.1', 'MIKROTIKRUMAH@|@admin', 'MIKROTIKRUMAH#|#eGJlaWR4mZ6X', 'MIKROTIKRUMAH%FamiiComp1302', 'MIKROTIKRUMAH^-', 'MIKROTIKRUMAH&Rp', 'MIKROTIKRUMAH*10', 'MIKROTIKRUMAH(1', 'MIKROTIKRUMAH)', 'MIKROTIKRUMAH=10', 'MIKROTIKRUMAH@!@disable');
$data['VIRTUALBOX'] = array ('1'=>'VIRTUALBOX!192.168.56.113','VIRTUALBOX@|@admin','VIRTUALBOX#|#aWRja2JlaWQ=','VIRTUALBOX%VIRTUALBOX-HOTSPOT','VIRTUALBOX^-','VIRTUALBOX&Rp','VIRTUALBOX*10','VIRTUALBOX(1','VIRTUALBOX)','VIRTUALBOX=10','VIRTUALBOX@!@disable');